### ISSUE TITLE
Todo list for `golemLaunch()`

### ISSUE THREAD

**Issue by ColinFay** [ThinkR-open/golem#303]
+ [x] `run_dev.R` shouldn't be inside the created app but in `{golem}` itself

+ [x] `get_buffer()` should be renamed, and use `cat()` instead of print. Maybe try to find a way to print colors. 

+ [x] `path` should be passed in `initialize`

+ [ ] The messages should be rewritten

+ [ ] `Sys.sleep()` should be changeable, and we default to `0`

+ [ ] Make `open_app()` default to user's default Viewer

+ [ ] Every function should be passed to `rstudioapi::hasFun()` (might be also true for other functions in the app)
